
// Package symbols is generated by gogll. Do not edit.
package symbols

import(
	"bytes"
	"fmt"
)

type Symbol interface{
	isSymbol()
	IsNonTerminal() bool
	String() string
}

func (NT) isSymbol() {}
func (T) isSymbol() {}

// NT is the type of non-terminals symbols
type NT int
const( 
	NT_LabelKey NT = iota
	NT_LabelOp 
	NT_LabelValue 
	NT_LogQuery 
	NT_LogSelector 
	NT_LogSelectorMember 
	NT_LogSelectorMembers 
	NT_MetricQuery 
	NT_Query 
)

// T is the type of terminals symbols
type T int
const( 
	T_0 T = iota // != 
	T_1  // !~ 
	T_2  // ( 
	T_3  // ) 
	T_4  // , 
	T_5  // = 
	T_6  // =~ 
	T_7  // [ 
	T_8  // ] 
	T_9  // by 
	T_10  // count_over_time 
	T_11  // duration 
	T_12  // level 
	T_13  // string 
	T_14  // sum 
	T_15  // var_name 
	T_16  // { 
	T_17  // } 
)

type Symbols []Symbol

func (ss Symbols) Equal(ss1 Symbols) bool {
	if len(ss) != len(ss1) {
		return false
	}
	for i, s := range ss {
		if s.String() != ss1[i].String() {
			return false
		}
	}
	return true
}

func (ss Symbols) String() string {
	w := new(bytes.Buffer)
	for i, s := range ss {
		if i > 0 {
			fmt.Fprint(w, " ")
		}
		fmt.Fprintf(w, "%s", s)
	}
	return w.String()
}

func (ss Symbols) Strings() []string {
	strs := make([]string, len(ss))
	for i, s := range ss {
		strs[i] = s.String()
	}
	return strs
}

func (NT) IsNonTerminal() bool {
	return true
}

func (T) IsNonTerminal() bool {
	return false
}

func (nt NT) String() string {
	return ntToString[nt]
}

func (t T) String() string {
	return tToString[t]
}

// IsNT returns true iff sym is a non-terminal symbol of the grammar
func IsNT(sym string) bool {
	_, exist := stringNT[sym]
	return exist
}

// ToNT returns the NT value of sym or panics if sym is not a non-terminal of the grammar
func ToNT(sym string) NT {
	nt, exist := stringNT[sym]
	if !exist {
		panic(fmt.Sprintf("No NT: %s", sym))
	}
	return nt
}

var ntToString = []string { 
	"LabelKey", /* NT_LabelKey */
	"LabelOp", /* NT_LabelOp */
	"LabelValue", /* NT_LabelValue */
	"LogQuery", /* NT_LogQuery */
	"LogSelector", /* NT_LogSelector */
	"LogSelectorMember", /* NT_LogSelectorMember */
	"LogSelectorMembers", /* NT_LogSelectorMembers */
	"MetricQuery", /* NT_MetricQuery */
	"Query", /* NT_Query */ 
}

var tToString = []string { 
	"!=", /* T_0 */
	"!~", /* T_1 */
	"(", /* T_2 */
	")", /* T_3 */
	",", /* T_4 */
	"=", /* T_5 */
	"=~", /* T_6 */
	"[", /* T_7 */
	"]", /* T_8 */
	"by", /* T_9 */
	"count_over_time", /* T_10 */
	"duration", /* T_11 */
	"level", /* T_12 */
	"string", /* T_13 */
	"sum", /* T_14 */
	"var_name", /* T_15 */
	"{", /* T_16 */
	"}", /* T_17 */ 
}

var stringNT = map[string]NT{ 
	"LabelKey":NT_LabelKey,
	"LabelOp":NT_LabelOp,
	"LabelValue":NT_LabelValue,
	"LogQuery":NT_LogQuery,
	"LogSelector":NT_LogSelector,
	"LogSelectorMember":NT_LogSelectorMember,
	"LogSelectorMembers":NT_LogSelectorMembers,
	"MetricQuery":NT_MetricQuery,
	"Query":NT_Query,
}
