version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: staticcheck -checks all,-ST1000 ./storage/... ./cmd/... ./api/loki
      - run: go test -p 1 -v -cover -coverprofile=c.out -race ./...
      - run: go tool cover -func=c.out
  release:
    docker:
      - image: cimg/base:2022.11
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: |
          docker build \
            -t $DOCKER_IMAGE:$CIRCLE_TAG \
            -t $DOCKER_IMAGE:latest \
            .
          echo $DOCKER_PASS | docker login ghcr.io -u $DOCKER_USER --password-stdin
          docker push $DOCKER_IMAGE:$CIRCLE_TAG
          docker push $DOCKER_IMAGE:latest
workflows:
  version: 2
  untagged-build:
    jobs:
      - build
  tagged-build:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
