
// Package slot is generated by gogll. Do not edit. 
package slot

import(
	"bytes"
	"fmt"
	
	"github.com/commentlens/loghouse/api/loki/logql/parser/symbols"
)

type Label int

const(
	LabelKey0R0 Label = iota
	LabelKey0R1
	LabelOp0R0
	LabelOp0R1
	LabelOp1R0
	LabelOp1R1
	LabelOp2R0
	LabelOp2R1
	LabelOp3R0
	LabelOp3R1
	LabelValue0R0
	LabelValue0R1
	LogQuery0R0
	LogQuery0R1
	LogSelector0R0
	LogSelector0R1
	LogSelector0R2
	LogSelector0R3
	LogSelectorMember0R0
	LogSelectorMember0R1
	LogSelectorMember0R2
	LogSelectorMember0R3
	LogSelectorMembers0R0
	LogSelectorMembers0R1
	LogSelectorMembers1R0
	LogSelectorMembers1R1
	LogSelectorMembers1R2
	LogSelectorMembers1R3
	MetricQuery0R0
	MetricQuery0R1
	MetricQuery0R2
	MetricQuery0R3
	MetricQuery0R4
	MetricQuery0R5
	MetricQuery0R6
	MetricQuery0R7
	MetricQuery0R8
	MetricQuery0R9
	MetricQuery0R10
	MetricQuery0R11
	MetricQuery0R12
	MetricQuery0R13
	MetricQuery0R14
	Query0R0
	Query0R1
	Query1R0
	Query1R1
)

type Slot struct {
	NT      symbols.NT
	Alt     int
	Pos     int
	Symbols symbols.Symbols
	Label 	Label
}

type Index struct {
	NT      symbols.NT
	Alt     int
	Pos     int
}

func GetAlternates(nt symbols.NT) []Label {
	alts, exist := alternates[nt]
	if !exist {
		panic(fmt.Sprintf("Invalid NT %s", nt))
	}
	return alts
}

func GetLabel(nt symbols.NT, alt, pos int) Label {
	l, exist := slotIndex[Index{nt,alt,pos}]
	if exist {
		return l
	}
	panic(fmt.Sprintf("Error: no slot label for NT=%s, alt=%d, pos=%d", nt, alt, pos))
}

func (l Label) EoR() bool {
	return l.Slot().EoR()
}

func (l Label) Head() symbols.NT {
	return l.Slot().NT
}

func (l Label) Index() Index {
	s := l.Slot()
	return Index{s.NT, s.Alt, s.Pos}
}

func (l Label) Alternate() int {
	return l.Slot().Alt
}

func (l Label) Pos() int {
	return l.Slot().Pos
}

func (l Label) Slot() *Slot {
	s, exist := slots[l]
	if !exist {
		panic(fmt.Sprintf("Invalid slot label %d", l))
	}
	return s
}

func (l Label) String() string {
	return l.Slot().String()
}

func (l Label) Symbols() symbols.Symbols {
	return l.Slot().Symbols
}

func (s *Slot) EoR() bool {
	return s.Pos >= len(s.Symbols)
}

func (s *Slot) String() string {
	buf := new(bytes.Buffer)
	fmt.Fprintf(buf, "%s : ", s.NT)
	for i, sym := range s.Symbols {
		if i == s.Pos {
			fmt.Fprintf(buf, "∙")
		}
		fmt.Fprintf(buf, "%s ", sym)
	}
	if s.Pos >= len(s.Symbols) {
		fmt.Fprintf(buf, "∙")
	}
	return buf.String()
}

var slots = map[Label]*Slot{ 
	LabelKey0R0: {
		symbols.NT_LabelKey, 0, 0, 
		symbols.Symbols{  
			symbols.T_15,
		}, 
		LabelKey0R0, 
	},
	LabelKey0R1: {
		symbols.NT_LabelKey, 0, 1, 
		symbols.Symbols{  
			symbols.T_15,
		}, 
		LabelKey0R1, 
	},
	LabelOp0R0: {
		symbols.NT_LabelOp, 0, 0, 
		symbols.Symbols{  
			symbols.T_5,
		}, 
		LabelOp0R0, 
	},
	LabelOp0R1: {
		symbols.NT_LabelOp, 0, 1, 
		symbols.Symbols{  
			symbols.T_5,
		}, 
		LabelOp0R1, 
	},
	LabelOp1R0: {
		symbols.NT_LabelOp, 1, 0, 
		symbols.Symbols{  
			symbols.T_0,
		}, 
		LabelOp1R0, 
	},
	LabelOp1R1: {
		symbols.NT_LabelOp, 1, 1, 
		symbols.Symbols{  
			symbols.T_0,
		}, 
		LabelOp1R1, 
	},
	LabelOp2R0: {
		symbols.NT_LabelOp, 2, 0, 
		symbols.Symbols{  
			symbols.T_6,
		}, 
		LabelOp2R0, 
	},
	LabelOp2R1: {
		symbols.NT_LabelOp, 2, 1, 
		symbols.Symbols{  
			symbols.T_6,
		}, 
		LabelOp2R1, 
	},
	LabelOp3R0: {
		symbols.NT_LabelOp, 3, 0, 
		symbols.Symbols{  
			symbols.T_1,
		}, 
		LabelOp3R0, 
	},
	LabelOp3R1: {
		symbols.NT_LabelOp, 3, 1, 
		symbols.Symbols{  
			symbols.T_1,
		}, 
		LabelOp3R1, 
	},
	LabelValue0R0: {
		symbols.NT_LabelValue, 0, 0, 
		symbols.Symbols{  
			symbols.T_13,
		}, 
		LabelValue0R0, 
	},
	LabelValue0R1: {
		symbols.NT_LabelValue, 0, 1, 
		symbols.Symbols{  
			symbols.T_13,
		}, 
		LabelValue0R1, 
	},
	LogQuery0R0: {
		symbols.NT_LogQuery, 0, 0, 
		symbols.Symbols{  
			symbols.NT_LogSelector,
		}, 
		LogQuery0R0, 
	},
	LogQuery0R1: {
		symbols.NT_LogQuery, 0, 1, 
		symbols.Symbols{  
			symbols.NT_LogSelector,
		}, 
		LogQuery0R1, 
	},
	LogSelector0R0: {
		symbols.NT_LogSelector, 0, 0, 
		symbols.Symbols{  
			symbols.T_16, 
			symbols.NT_LogSelectorMembers, 
			symbols.T_17,
		}, 
		LogSelector0R0, 
	},
	LogSelector0R1: {
		symbols.NT_LogSelector, 0, 1, 
		symbols.Symbols{  
			symbols.T_16, 
			symbols.NT_LogSelectorMembers, 
			symbols.T_17,
		}, 
		LogSelector0R1, 
	},
	LogSelector0R2: {
		symbols.NT_LogSelector, 0, 2, 
		symbols.Symbols{  
			symbols.T_16, 
			symbols.NT_LogSelectorMembers, 
			symbols.T_17,
		}, 
		LogSelector0R2, 
	},
	LogSelector0R3: {
		symbols.NT_LogSelector, 0, 3, 
		symbols.Symbols{  
			symbols.T_16, 
			symbols.NT_LogSelectorMembers, 
			symbols.T_17,
		}, 
		LogSelector0R3, 
	},
	LogSelectorMember0R0: {
		symbols.NT_LogSelectorMember, 0, 0, 
		symbols.Symbols{  
			symbols.NT_LabelKey, 
			symbols.NT_LabelOp, 
			symbols.NT_LabelValue,
		}, 
		LogSelectorMember0R0, 
	},
	LogSelectorMember0R1: {
		symbols.NT_LogSelectorMember, 0, 1, 
		symbols.Symbols{  
			symbols.NT_LabelKey, 
			symbols.NT_LabelOp, 
			symbols.NT_LabelValue,
		}, 
		LogSelectorMember0R1, 
	},
	LogSelectorMember0R2: {
		symbols.NT_LogSelectorMember, 0, 2, 
		symbols.Symbols{  
			symbols.NT_LabelKey, 
			symbols.NT_LabelOp, 
			symbols.NT_LabelValue,
		}, 
		LogSelectorMember0R2, 
	},
	LogSelectorMember0R3: {
		symbols.NT_LogSelectorMember, 0, 3, 
		symbols.Symbols{  
			symbols.NT_LabelKey, 
			symbols.NT_LabelOp, 
			symbols.NT_LabelValue,
		}, 
		LogSelectorMember0R3, 
	},
	LogSelectorMembers0R0: {
		symbols.NT_LogSelectorMembers, 0, 0, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember,
		}, 
		LogSelectorMembers0R0, 
	},
	LogSelectorMembers0R1: {
		symbols.NT_LogSelectorMembers, 0, 1, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember,
		}, 
		LogSelectorMembers0R1, 
	},
	LogSelectorMembers1R0: {
		symbols.NT_LogSelectorMembers, 1, 0, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember, 
			symbols.T_4, 
			symbols.NT_LogSelectorMembers,
		}, 
		LogSelectorMembers1R0, 
	},
	LogSelectorMembers1R1: {
		symbols.NT_LogSelectorMembers, 1, 1, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember, 
			symbols.T_4, 
			symbols.NT_LogSelectorMembers,
		}, 
		LogSelectorMembers1R1, 
	},
	LogSelectorMembers1R2: {
		symbols.NT_LogSelectorMembers, 1, 2, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember, 
			symbols.T_4, 
			symbols.NT_LogSelectorMembers,
		}, 
		LogSelectorMembers1R2, 
	},
	LogSelectorMembers1R3: {
		symbols.NT_LogSelectorMembers, 1, 3, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember, 
			symbols.T_4, 
			symbols.NT_LogSelectorMembers,
		}, 
		LogSelectorMembers1R3, 
	},
	MetricQuery0R0: {
		symbols.NT_MetricQuery, 0, 0, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R0, 
	},
	MetricQuery0R1: {
		symbols.NT_MetricQuery, 0, 1, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R1, 
	},
	MetricQuery0R2: {
		symbols.NT_MetricQuery, 0, 2, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R2, 
	},
	MetricQuery0R3: {
		symbols.NT_MetricQuery, 0, 3, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R3, 
	},
	MetricQuery0R4: {
		symbols.NT_MetricQuery, 0, 4, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R4, 
	},
	MetricQuery0R5: {
		symbols.NT_MetricQuery, 0, 5, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R5, 
	},
	MetricQuery0R6: {
		symbols.NT_MetricQuery, 0, 6, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R6, 
	},
	MetricQuery0R7: {
		symbols.NT_MetricQuery, 0, 7, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R7, 
	},
	MetricQuery0R8: {
		symbols.NT_MetricQuery, 0, 8, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R8, 
	},
	MetricQuery0R9: {
		symbols.NT_MetricQuery, 0, 9, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R9, 
	},
	MetricQuery0R10: {
		symbols.NT_MetricQuery, 0, 10, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R10, 
	},
	MetricQuery0R11: {
		symbols.NT_MetricQuery, 0, 11, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R11, 
	},
	MetricQuery0R12: {
		symbols.NT_MetricQuery, 0, 12, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R12, 
	},
	MetricQuery0R13: {
		symbols.NT_MetricQuery, 0, 13, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R13, 
	},
	MetricQuery0R14: {
		symbols.NT_MetricQuery, 0, 14, 
		symbols.Symbols{  
			symbols.T_14, 
			symbols.T_9, 
			symbols.T_2, 
			symbols.T_12, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_10, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_7, 
			symbols.T_11, 
			symbols.T_8, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R14, 
	},
	Query0R0: {
		symbols.NT_Query, 0, 0, 
		symbols.Symbols{  
			symbols.NT_LogQuery,
		}, 
		Query0R0, 
	},
	Query0R1: {
		symbols.NT_Query, 0, 1, 
		symbols.Symbols{  
			symbols.NT_LogQuery,
		}, 
		Query0R1, 
	},
	Query1R0: {
		symbols.NT_Query, 1, 0, 
		symbols.Symbols{  
			symbols.NT_MetricQuery,
		}, 
		Query1R0, 
	},
	Query1R1: {
		symbols.NT_Query, 1, 1, 
		symbols.Symbols{  
			symbols.NT_MetricQuery,
		}, 
		Query1R1, 
	},
}

var slotIndex = map[Index]Label { 
	Index{ symbols.NT_LabelKey,0,0 }: LabelKey0R0,
	Index{ symbols.NT_LabelKey,0,1 }: LabelKey0R1,
	Index{ symbols.NT_LabelOp,0,0 }: LabelOp0R0,
	Index{ symbols.NT_LabelOp,0,1 }: LabelOp0R1,
	Index{ symbols.NT_LabelOp,1,0 }: LabelOp1R0,
	Index{ symbols.NT_LabelOp,1,1 }: LabelOp1R1,
	Index{ symbols.NT_LabelOp,2,0 }: LabelOp2R0,
	Index{ symbols.NT_LabelOp,2,1 }: LabelOp2R1,
	Index{ symbols.NT_LabelOp,3,0 }: LabelOp3R0,
	Index{ symbols.NT_LabelOp,3,1 }: LabelOp3R1,
	Index{ symbols.NT_LabelValue,0,0 }: LabelValue0R0,
	Index{ symbols.NT_LabelValue,0,1 }: LabelValue0R1,
	Index{ symbols.NT_LogQuery,0,0 }: LogQuery0R0,
	Index{ symbols.NT_LogQuery,0,1 }: LogQuery0R1,
	Index{ symbols.NT_LogSelector,0,0 }: LogSelector0R0,
	Index{ symbols.NT_LogSelector,0,1 }: LogSelector0R1,
	Index{ symbols.NT_LogSelector,0,2 }: LogSelector0R2,
	Index{ symbols.NT_LogSelector,0,3 }: LogSelector0R3,
	Index{ symbols.NT_LogSelectorMember,0,0 }: LogSelectorMember0R0,
	Index{ symbols.NT_LogSelectorMember,0,1 }: LogSelectorMember0R1,
	Index{ symbols.NT_LogSelectorMember,0,2 }: LogSelectorMember0R2,
	Index{ symbols.NT_LogSelectorMember,0,3 }: LogSelectorMember0R3,
	Index{ symbols.NT_LogSelectorMembers,0,0 }: LogSelectorMembers0R0,
	Index{ symbols.NT_LogSelectorMembers,0,1 }: LogSelectorMembers0R1,
	Index{ symbols.NT_LogSelectorMembers,1,0 }: LogSelectorMembers1R0,
	Index{ symbols.NT_LogSelectorMembers,1,1 }: LogSelectorMembers1R1,
	Index{ symbols.NT_LogSelectorMembers,1,2 }: LogSelectorMembers1R2,
	Index{ symbols.NT_LogSelectorMembers,1,3 }: LogSelectorMembers1R3,
	Index{ symbols.NT_MetricQuery,0,0 }: MetricQuery0R0,
	Index{ symbols.NT_MetricQuery,0,1 }: MetricQuery0R1,
	Index{ symbols.NT_MetricQuery,0,2 }: MetricQuery0R2,
	Index{ symbols.NT_MetricQuery,0,3 }: MetricQuery0R3,
	Index{ symbols.NT_MetricQuery,0,4 }: MetricQuery0R4,
	Index{ symbols.NT_MetricQuery,0,5 }: MetricQuery0R5,
	Index{ symbols.NT_MetricQuery,0,6 }: MetricQuery0R6,
	Index{ symbols.NT_MetricQuery,0,7 }: MetricQuery0R7,
	Index{ symbols.NT_MetricQuery,0,8 }: MetricQuery0R8,
	Index{ symbols.NT_MetricQuery,0,9 }: MetricQuery0R9,
	Index{ symbols.NT_MetricQuery,0,10 }: MetricQuery0R10,
	Index{ symbols.NT_MetricQuery,0,11 }: MetricQuery0R11,
	Index{ symbols.NT_MetricQuery,0,12 }: MetricQuery0R12,
	Index{ symbols.NT_MetricQuery,0,13 }: MetricQuery0R13,
	Index{ symbols.NT_MetricQuery,0,14 }: MetricQuery0R14,
	Index{ symbols.NT_Query,0,0 }: Query0R0,
	Index{ symbols.NT_Query,0,1 }: Query0R1,
	Index{ symbols.NT_Query,1,0 }: Query1R0,
	Index{ symbols.NT_Query,1,1 }: Query1R1,
}

var alternates = map[symbols.NT][]Label{ 
	symbols.NT_Query:[]Label{ Query0R0,Query1R0 },
	symbols.NT_LogQuery:[]Label{ LogQuery0R0 },
	symbols.NT_LogSelector:[]Label{ LogSelector0R0 },
	symbols.NT_LogSelectorMembers:[]Label{ LogSelectorMembers0R0,LogSelectorMembers1R0 },
	symbols.NT_LogSelectorMember:[]Label{ LogSelectorMember0R0 },
	symbols.NT_LabelOp:[]Label{ LabelOp0R0,LabelOp1R0,LabelOp2R0,LabelOp3R0 },
	symbols.NT_LabelKey:[]Label{ LabelKey0R0 },
	symbols.NT_LabelValue:[]Label{ LabelValue0R0 },
	symbols.NT_MetricQuery:[]Label{ MetricQuery0R0 },
}

