
// Package slot is generated by gogll. Do not edit. 
package slot

import(
	"bytes"
	"fmt"
	
	"github.com/commentlens/loghouse/api/loki/logql/parser/symbols"
)

type Label int

const(
	LabelFilter0R0 Label = iota
	LabelFilter0R1
	LabelFilter0R2
	LabelFilter0R3
	LabelFilter0R4
	LabelFilterOp0R0
	LabelFilterOp0R1
	LabelFilterOp1R0
	LabelFilterOp1R1
	LabelFilterOp2R0
	LabelFilterOp2R1
	LabelFilterOp3R0
	LabelFilterOp3R1
	LabelFilterOp4R0
	LabelFilterOp4R1
	LabelFilterOp5R0
	LabelFilterOp5R1
	LabelFilterOp6R0
	LabelFilterOp6R1
	LabelFilterOp7R0
	LabelFilterOp7R1
	LabelKey0R0
	LabelKey0R1
	LineFilter0R0
	LineFilter0R1
	LineFilter0R2
	LineFilterOp0R0
	LineFilterOp0R1
	LineFilterOp1R0
	LineFilterOp1R1
	LineFilterOp2R0
	LineFilterOp2R1
	LineFilterOp3R0
	LineFilterOp3R1
	LogQuery0R0
	LogQuery0R1
	LogQuery0R2
	LogSelector0R0
	LogSelector0R1
	LogSelector0R2
	LogSelector0R3
	LogSelectorMember0R0
	LogSelectorMember0R1
	LogSelectorMember0R2
	LogSelectorMember0R3
	LogSelectorMembers0R0
	LogSelectorMembers0R1
	LogSelectorMembers1R0
	LogSelectorMembers1R1
	LogSelectorMembers1R2
	LogSelectorMembers1R3
	LogSelectorMembersMaybe0R0
	LogSelectorMembersMaybe1R0
	LogSelectorMembersMaybe1R1
	LogSelectorOp0R0
	LogSelectorOp0R1
	LogSelectorOp1R0
	LogSelectorOp1R1
	LogSelectorOp2R0
	LogSelectorOp2R1
	LogSelectorOp3R0
	LogSelectorOp3R1
	MetricQuery0R0
	MetricQuery0R1
	MetricQuery0R2
	MetricQuery0R3
	MetricQuery0R4
	MetricQuery0R5
	MetricQuery0R6
	MetricQuery0R7
	MetricQuery0R8
	MetricQuery0R9
	MetricQuery0R10
	MetricQuery0R11
	MetricQuery0R12
	MetricQuery0R13
	MetricQuery0R14
	NestedLabelKey0R0
	NestedLabelKey0R1
	NestedLabelKey1R0
	NestedLabelKey1R1
	NestedLabelKey1R2
	NestedLabelKey1R3
	Pipeline0R0
	Pipeline0R1
	Pipeline1R0
	Pipeline1R1
	Pipelines0R0
	Pipelines0R1
	Pipelines1R0
	Pipelines1R1
	Pipelines1R2
	PipelinesMaybe0R0
	PipelinesMaybe1R0
	PipelinesMaybe1R1
	Query0R0
	Query0R1
	Query1R0
	Query1R1
)

type Slot struct {
	NT      symbols.NT
	Alt     int
	Pos     int
	Symbols symbols.Symbols
	Label 	Label
}

type Index struct {
	NT      symbols.NT
	Alt     int
	Pos     int
}

func GetAlternates(nt symbols.NT) []Label {
	alts, exist := alternates[nt]
	if !exist {
		panic(fmt.Sprintf("Invalid NT %s", nt))
	}
	return alts
}

func GetLabel(nt symbols.NT, alt, pos int) Label {
	l, exist := slotIndex[Index{nt,alt,pos}]
	if exist {
		return l
	}
	panic(fmt.Sprintf("Error: no slot label for NT=%s, alt=%d, pos=%d", nt, alt, pos))
}

func (l Label) EoR() bool {
	return l.Slot().EoR()
}

func (l Label) Head() symbols.NT {
	return l.Slot().NT
}

func (l Label) Index() Index {
	s := l.Slot()
	return Index{s.NT, s.Alt, s.Pos}
}

func (l Label) Alternate() int {
	return l.Slot().Alt
}

func (l Label) Pos() int {
	return l.Slot().Pos
}

func (l Label) Slot() *Slot {
	s, exist := slots[l]
	if !exist {
		panic(fmt.Sprintf("Invalid slot label %d", l))
	}
	return s
}

func (l Label) String() string {
	return l.Slot().String()
}

func (l Label) Symbols() symbols.Symbols {
	return l.Slot().Symbols
}

func (s *Slot) EoR() bool {
	return s.Pos >= len(s.Symbols)
}

func (s *Slot) String() string {
	buf := new(bytes.Buffer)
	fmt.Fprintf(buf, "%s : ", s.NT)
	for i, sym := range s.Symbols {
		if i == s.Pos {
			fmt.Fprintf(buf, "∙")
		}
		fmt.Fprintf(buf, "%s ", sym)
	}
	if s.Pos >= len(s.Symbols) {
		fmt.Fprintf(buf, "∙")
	}
	return buf.String()
}

var slots = map[Label]*Slot{ 
	LabelFilter0R0: {
		symbols.NT_LabelFilter, 0, 0, 
		symbols.Symbols{  
			symbols.T_22, 
			symbols.NT_NestedLabelKey, 
			symbols.NT_LabelFilterOp, 
			symbols.T_18,
		}, 
		LabelFilter0R0, 
	},
	LabelFilter0R1: {
		symbols.NT_LabelFilter, 0, 1, 
		symbols.Symbols{  
			symbols.T_22, 
			symbols.NT_NestedLabelKey, 
			symbols.NT_LabelFilterOp, 
			symbols.T_18,
		}, 
		LabelFilter0R1, 
	},
	LabelFilter0R2: {
		symbols.NT_LabelFilter, 0, 2, 
		symbols.Symbols{  
			symbols.T_22, 
			symbols.NT_NestedLabelKey, 
			symbols.NT_LabelFilterOp, 
			symbols.T_18,
		}, 
		LabelFilter0R2, 
	},
	LabelFilter0R3: {
		symbols.NT_LabelFilter, 0, 3, 
		symbols.Symbols{  
			symbols.T_22, 
			symbols.NT_NestedLabelKey, 
			symbols.NT_LabelFilterOp, 
			symbols.T_18,
		}, 
		LabelFilter0R3, 
	},
	LabelFilter0R4: {
		symbols.NT_LabelFilter, 0, 4, 
		symbols.Symbols{  
			symbols.T_22, 
			symbols.NT_NestedLabelKey, 
			symbols.NT_LabelFilterOp, 
			symbols.T_18,
		}, 
		LabelFilter0R4, 
	},
	LabelFilterOp0R0: {
		symbols.NT_LabelFilterOp, 0, 0, 
		symbols.Symbols{  
			symbols.T_8,
		}, 
		LabelFilterOp0R0, 
	},
	LabelFilterOp0R1: {
		symbols.NT_LabelFilterOp, 0, 1, 
		symbols.Symbols{  
			symbols.T_8,
		}, 
		LabelFilterOp0R1, 
	},
	LabelFilterOp1R0: {
		symbols.NT_LabelFilterOp, 1, 0, 
		symbols.Symbols{  
			symbols.T_0,
		}, 
		LabelFilterOp1R0, 
	},
	LabelFilterOp1R1: {
		symbols.NT_LabelFilterOp, 1, 1, 
		symbols.Symbols{  
			symbols.T_0,
		}, 
		LabelFilterOp1R1, 
	},
	LabelFilterOp2R0: {
		symbols.NT_LabelFilterOp, 2, 0, 
		symbols.Symbols{  
			symbols.T_9,
		}, 
		LabelFilterOp2R0, 
	},
	LabelFilterOp2R1: {
		symbols.NT_LabelFilterOp, 2, 1, 
		symbols.Symbols{  
			symbols.T_9,
		}, 
		LabelFilterOp2R1, 
	},
	LabelFilterOp3R0: {
		symbols.NT_LabelFilterOp, 3, 0, 
		symbols.Symbols{  
			symbols.T_1,
		}, 
		LabelFilterOp3R0, 
	},
	LabelFilterOp3R1: {
		symbols.NT_LabelFilterOp, 3, 1, 
		symbols.Symbols{  
			symbols.T_1,
		}, 
		LabelFilterOp3R1, 
	},
	LabelFilterOp4R0: {
		symbols.NT_LabelFilterOp, 4, 0, 
		symbols.Symbols{  
			symbols.T_11,
		}, 
		LabelFilterOp4R0, 
	},
	LabelFilterOp4R1: {
		symbols.NT_LabelFilterOp, 4, 1, 
		symbols.Symbols{  
			symbols.T_11,
		}, 
		LabelFilterOp4R1, 
	},
	LabelFilterOp5R0: {
		symbols.NT_LabelFilterOp, 5, 0, 
		symbols.Symbols{  
			symbols.T_10,
		}, 
		LabelFilterOp5R0, 
	},
	LabelFilterOp5R1: {
		symbols.NT_LabelFilterOp, 5, 1, 
		symbols.Symbols{  
			symbols.T_10,
		}, 
		LabelFilterOp5R1, 
	},
	LabelFilterOp6R0: {
		symbols.NT_LabelFilterOp, 6, 0, 
		symbols.Symbols{  
			symbols.T_7,
		}, 
		LabelFilterOp6R0, 
	},
	LabelFilterOp6R1: {
		symbols.NT_LabelFilterOp, 6, 1, 
		symbols.Symbols{  
			symbols.T_7,
		}, 
		LabelFilterOp6R1, 
	},
	LabelFilterOp7R0: {
		symbols.NT_LabelFilterOp, 7, 0, 
		symbols.Symbols{  
			symbols.T_6,
		}, 
		LabelFilterOp7R0, 
	},
	LabelFilterOp7R1: {
		symbols.NT_LabelFilterOp, 7, 1, 
		symbols.Symbols{  
			symbols.T_6,
		}, 
		LabelFilterOp7R1, 
	},
	LabelKey0R0: {
		symbols.NT_LabelKey, 0, 0, 
		symbols.Symbols{  
			symbols.T_20,
		}, 
		LabelKey0R0, 
	},
	LabelKey0R1: {
		symbols.NT_LabelKey, 0, 1, 
		symbols.Symbols{  
			symbols.T_20,
		}, 
		LabelKey0R1, 
	},
	LineFilter0R0: {
		symbols.NT_LineFilter, 0, 0, 
		symbols.Symbols{  
			symbols.NT_LineFilterOp, 
			symbols.T_18,
		}, 
		LineFilter0R0, 
	},
	LineFilter0R1: {
		symbols.NT_LineFilter, 0, 1, 
		symbols.Symbols{  
			symbols.NT_LineFilterOp, 
			symbols.T_18,
		}, 
		LineFilter0R1, 
	},
	LineFilter0R2: {
		symbols.NT_LineFilter, 0, 2, 
		symbols.Symbols{  
			symbols.NT_LineFilterOp, 
			symbols.T_18,
		}, 
		LineFilter0R2, 
	},
	LineFilterOp0R0: {
		symbols.NT_LineFilterOp, 0, 0, 
		symbols.Symbols{  
			symbols.T_23,
		}, 
		LineFilterOp0R0, 
	},
	LineFilterOp0R1: {
		symbols.NT_LineFilterOp, 0, 1, 
		symbols.Symbols{  
			symbols.T_23,
		}, 
		LineFilterOp0R1, 
	},
	LineFilterOp1R0: {
		symbols.NT_LineFilterOp, 1, 0, 
		symbols.Symbols{  
			symbols.T_0,
		}, 
		LineFilterOp1R0, 
	},
	LineFilterOp1R1: {
		symbols.NT_LineFilterOp, 1, 1, 
		symbols.Symbols{  
			symbols.T_0,
		}, 
		LineFilterOp1R1, 
	},
	LineFilterOp2R0: {
		symbols.NT_LineFilterOp, 2, 0, 
		symbols.Symbols{  
			symbols.T_24,
		}, 
		LineFilterOp2R0, 
	},
	LineFilterOp2R1: {
		symbols.NT_LineFilterOp, 2, 1, 
		symbols.Symbols{  
			symbols.T_24,
		}, 
		LineFilterOp2R1, 
	},
	LineFilterOp3R0: {
		symbols.NT_LineFilterOp, 3, 0, 
		symbols.Symbols{  
			symbols.T_1,
		}, 
		LineFilterOp3R0, 
	},
	LineFilterOp3R1: {
		symbols.NT_LineFilterOp, 3, 1, 
		symbols.Symbols{  
			symbols.T_1,
		}, 
		LineFilterOp3R1, 
	},
	LogQuery0R0: {
		symbols.NT_LogQuery, 0, 0, 
		symbols.Symbols{  
			symbols.NT_LogSelector, 
			symbols.NT_PipelinesMaybe,
		}, 
		LogQuery0R0, 
	},
	LogQuery0R1: {
		symbols.NT_LogQuery, 0, 1, 
		symbols.Symbols{  
			symbols.NT_LogSelector, 
			symbols.NT_PipelinesMaybe,
		}, 
		LogQuery0R1, 
	},
	LogQuery0R2: {
		symbols.NT_LogQuery, 0, 2, 
		symbols.Symbols{  
			symbols.NT_LogSelector, 
			symbols.NT_PipelinesMaybe,
		}, 
		LogQuery0R2, 
	},
	LogSelector0R0: {
		symbols.NT_LogSelector, 0, 0, 
		symbols.Symbols{  
			symbols.T_21, 
			symbols.NT_LogSelectorMembersMaybe, 
			symbols.T_25,
		}, 
		LogSelector0R0, 
	},
	LogSelector0R1: {
		symbols.NT_LogSelector, 0, 1, 
		symbols.Symbols{  
			symbols.T_21, 
			symbols.NT_LogSelectorMembersMaybe, 
			symbols.T_25,
		}, 
		LogSelector0R1, 
	},
	LogSelector0R2: {
		symbols.NT_LogSelector, 0, 2, 
		symbols.Symbols{  
			symbols.T_21, 
			symbols.NT_LogSelectorMembersMaybe, 
			symbols.T_25,
		}, 
		LogSelector0R2, 
	},
	LogSelector0R3: {
		symbols.NT_LogSelector, 0, 3, 
		symbols.Symbols{  
			symbols.T_21, 
			symbols.NT_LogSelectorMembersMaybe, 
			symbols.T_25,
		}, 
		LogSelector0R3, 
	},
	LogSelectorMember0R0: {
		symbols.NT_LogSelectorMember, 0, 0, 
		symbols.Symbols{  
			symbols.NT_LabelKey, 
			symbols.NT_LogSelectorOp, 
			symbols.T_18,
		}, 
		LogSelectorMember0R0, 
	},
	LogSelectorMember0R1: {
		symbols.NT_LogSelectorMember, 0, 1, 
		symbols.Symbols{  
			symbols.NT_LabelKey, 
			symbols.NT_LogSelectorOp, 
			symbols.T_18,
		}, 
		LogSelectorMember0R1, 
	},
	LogSelectorMember0R2: {
		symbols.NT_LogSelectorMember, 0, 2, 
		symbols.Symbols{  
			symbols.NT_LabelKey, 
			symbols.NT_LogSelectorOp, 
			symbols.T_18,
		}, 
		LogSelectorMember0R2, 
	},
	LogSelectorMember0R3: {
		symbols.NT_LogSelectorMember, 0, 3, 
		symbols.Symbols{  
			symbols.NT_LabelKey, 
			symbols.NT_LogSelectorOp, 
			symbols.T_18,
		}, 
		LogSelectorMember0R3, 
	},
	LogSelectorMembers0R0: {
		symbols.NT_LogSelectorMembers, 0, 0, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember,
		}, 
		LogSelectorMembers0R0, 
	},
	LogSelectorMembers0R1: {
		symbols.NT_LogSelectorMembers, 0, 1, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember,
		}, 
		LogSelectorMembers0R1, 
	},
	LogSelectorMembers1R0: {
		symbols.NT_LogSelectorMembers, 1, 0, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember, 
			symbols.T_4, 
			symbols.NT_LogSelectorMembers,
		}, 
		LogSelectorMembers1R0, 
	},
	LogSelectorMembers1R1: {
		symbols.NT_LogSelectorMembers, 1, 1, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember, 
			symbols.T_4, 
			symbols.NT_LogSelectorMembers,
		}, 
		LogSelectorMembers1R1, 
	},
	LogSelectorMembers1R2: {
		symbols.NT_LogSelectorMembers, 1, 2, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember, 
			symbols.T_4, 
			symbols.NT_LogSelectorMembers,
		}, 
		LogSelectorMembers1R2, 
	},
	LogSelectorMembers1R3: {
		symbols.NT_LogSelectorMembers, 1, 3, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMember, 
			symbols.T_4, 
			symbols.NT_LogSelectorMembers,
		}, 
		LogSelectorMembers1R3, 
	},
	LogSelectorMembersMaybe0R0: {
		symbols.NT_LogSelectorMembersMaybe, 0, 0, 
		symbols.Symbols{ 
		}, 
		LogSelectorMembersMaybe0R0, 
	},
	LogSelectorMembersMaybe1R0: {
		symbols.NT_LogSelectorMembersMaybe, 1, 0, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMembers,
		}, 
		LogSelectorMembersMaybe1R0, 
	},
	LogSelectorMembersMaybe1R1: {
		symbols.NT_LogSelectorMembersMaybe, 1, 1, 
		symbols.Symbols{  
			symbols.NT_LogSelectorMembers,
		}, 
		LogSelectorMembersMaybe1R1, 
	},
	LogSelectorOp0R0: {
		symbols.NT_LogSelectorOp, 0, 0, 
		symbols.Symbols{  
			symbols.T_8,
		}, 
		LogSelectorOp0R0, 
	},
	LogSelectorOp0R1: {
		symbols.NT_LogSelectorOp, 0, 1, 
		symbols.Symbols{  
			symbols.T_8,
		}, 
		LogSelectorOp0R1, 
	},
	LogSelectorOp1R0: {
		symbols.NT_LogSelectorOp, 1, 0, 
		symbols.Symbols{  
			symbols.T_0,
		}, 
		LogSelectorOp1R0, 
	},
	LogSelectorOp1R1: {
		symbols.NT_LogSelectorOp, 1, 1, 
		symbols.Symbols{  
			symbols.T_0,
		}, 
		LogSelectorOp1R1, 
	},
	LogSelectorOp2R0: {
		symbols.NT_LogSelectorOp, 2, 0, 
		symbols.Symbols{  
			symbols.T_9,
		}, 
		LogSelectorOp2R0, 
	},
	LogSelectorOp2R1: {
		symbols.NT_LogSelectorOp, 2, 1, 
		symbols.Symbols{  
			symbols.T_9,
		}, 
		LogSelectorOp2R1, 
	},
	LogSelectorOp3R0: {
		symbols.NT_LogSelectorOp, 3, 0, 
		symbols.Symbols{  
			symbols.T_1,
		}, 
		LogSelectorOp3R0, 
	},
	LogSelectorOp3R1: {
		symbols.NT_LogSelectorOp, 3, 1, 
		symbols.Symbols{  
			symbols.T_1,
		}, 
		LogSelectorOp3R1, 
	},
	MetricQuery0R0: {
		symbols.NT_MetricQuery, 0, 0, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R0, 
	},
	MetricQuery0R1: {
		symbols.NT_MetricQuery, 0, 1, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R1, 
	},
	MetricQuery0R2: {
		symbols.NT_MetricQuery, 0, 2, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R2, 
	},
	MetricQuery0R3: {
		symbols.NT_MetricQuery, 0, 3, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R3, 
	},
	MetricQuery0R4: {
		symbols.NT_MetricQuery, 0, 4, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R4, 
	},
	MetricQuery0R5: {
		symbols.NT_MetricQuery, 0, 5, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R5, 
	},
	MetricQuery0R6: {
		symbols.NT_MetricQuery, 0, 6, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R6, 
	},
	MetricQuery0R7: {
		symbols.NT_MetricQuery, 0, 7, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R7, 
	},
	MetricQuery0R8: {
		symbols.NT_MetricQuery, 0, 8, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R8, 
	},
	MetricQuery0R9: {
		symbols.NT_MetricQuery, 0, 9, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R9, 
	},
	MetricQuery0R10: {
		symbols.NT_MetricQuery, 0, 10, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R10, 
	},
	MetricQuery0R11: {
		symbols.NT_MetricQuery, 0, 11, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R11, 
	},
	MetricQuery0R12: {
		symbols.NT_MetricQuery, 0, 12, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R12, 
	},
	MetricQuery0R13: {
		symbols.NT_MetricQuery, 0, 13, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R13, 
	},
	MetricQuery0R14: {
		symbols.NT_MetricQuery, 0, 14, 
		symbols.Symbols{  
			symbols.T_19, 
			symbols.T_14, 
			symbols.T_2, 
			symbols.T_17, 
			symbols.T_3, 
			symbols.T_2, 
			symbols.T_15, 
			symbols.T_2, 
			symbols.NT_LogQuery, 
			symbols.T_12, 
			symbols.T_16, 
			symbols.T_13, 
			symbols.T_3, 
			symbols.T_3,
		}, 
		MetricQuery0R14, 
	},
	NestedLabelKey0R0: {
		symbols.NT_NestedLabelKey, 0, 0, 
		symbols.Symbols{  
			symbols.T_20,
		}, 
		NestedLabelKey0R0, 
	},
	NestedLabelKey0R1: {
		symbols.NT_NestedLabelKey, 0, 1, 
		symbols.Symbols{  
			symbols.T_20,
		}, 
		NestedLabelKey0R1, 
	},
	NestedLabelKey1R0: {
		symbols.NT_NestedLabelKey, 1, 0, 
		symbols.Symbols{  
			symbols.T_20, 
			symbols.T_5, 
			symbols.NT_NestedLabelKey,
		}, 
		NestedLabelKey1R0, 
	},
	NestedLabelKey1R1: {
		symbols.NT_NestedLabelKey, 1, 1, 
		symbols.Symbols{  
			symbols.T_20, 
			symbols.T_5, 
			symbols.NT_NestedLabelKey,
		}, 
		NestedLabelKey1R1, 
	},
	NestedLabelKey1R2: {
		symbols.NT_NestedLabelKey, 1, 2, 
		symbols.Symbols{  
			symbols.T_20, 
			symbols.T_5, 
			symbols.NT_NestedLabelKey,
		}, 
		NestedLabelKey1R2, 
	},
	NestedLabelKey1R3: {
		symbols.NT_NestedLabelKey, 1, 3, 
		symbols.Symbols{  
			symbols.T_20, 
			symbols.T_5, 
			symbols.NT_NestedLabelKey,
		}, 
		NestedLabelKey1R3, 
	},
	Pipeline0R0: {
		symbols.NT_Pipeline, 0, 0, 
		symbols.Symbols{  
			symbols.NT_LineFilter,
		}, 
		Pipeline0R0, 
	},
	Pipeline0R1: {
		symbols.NT_Pipeline, 0, 1, 
		symbols.Symbols{  
			symbols.NT_LineFilter,
		}, 
		Pipeline0R1, 
	},
	Pipeline1R0: {
		symbols.NT_Pipeline, 1, 0, 
		symbols.Symbols{  
			symbols.NT_LabelFilter,
		}, 
		Pipeline1R0, 
	},
	Pipeline1R1: {
		symbols.NT_Pipeline, 1, 1, 
		symbols.Symbols{  
			symbols.NT_LabelFilter,
		}, 
		Pipeline1R1, 
	},
	Pipelines0R0: {
		symbols.NT_Pipelines, 0, 0, 
		symbols.Symbols{  
			symbols.NT_Pipeline,
		}, 
		Pipelines0R0, 
	},
	Pipelines0R1: {
		symbols.NT_Pipelines, 0, 1, 
		symbols.Symbols{  
			symbols.NT_Pipeline,
		}, 
		Pipelines0R1, 
	},
	Pipelines1R0: {
		symbols.NT_Pipelines, 1, 0, 
		symbols.Symbols{  
			symbols.NT_Pipeline, 
			symbols.NT_Pipelines,
		}, 
		Pipelines1R0, 
	},
	Pipelines1R1: {
		symbols.NT_Pipelines, 1, 1, 
		symbols.Symbols{  
			symbols.NT_Pipeline, 
			symbols.NT_Pipelines,
		}, 
		Pipelines1R1, 
	},
	Pipelines1R2: {
		symbols.NT_Pipelines, 1, 2, 
		symbols.Symbols{  
			symbols.NT_Pipeline, 
			symbols.NT_Pipelines,
		}, 
		Pipelines1R2, 
	},
	PipelinesMaybe0R0: {
		symbols.NT_PipelinesMaybe, 0, 0, 
		symbols.Symbols{ 
		}, 
		PipelinesMaybe0R0, 
	},
	PipelinesMaybe1R0: {
		symbols.NT_PipelinesMaybe, 1, 0, 
		symbols.Symbols{  
			symbols.NT_Pipelines,
		}, 
		PipelinesMaybe1R0, 
	},
	PipelinesMaybe1R1: {
		symbols.NT_PipelinesMaybe, 1, 1, 
		symbols.Symbols{  
			symbols.NT_Pipelines,
		}, 
		PipelinesMaybe1R1, 
	},
	Query0R0: {
		symbols.NT_Query, 0, 0, 
		symbols.Symbols{  
			symbols.NT_LogQuery,
		}, 
		Query0R0, 
	},
	Query0R1: {
		symbols.NT_Query, 0, 1, 
		symbols.Symbols{  
			symbols.NT_LogQuery,
		}, 
		Query0R1, 
	},
	Query1R0: {
		symbols.NT_Query, 1, 0, 
		symbols.Symbols{  
			symbols.NT_MetricQuery,
		}, 
		Query1R0, 
	},
	Query1R1: {
		symbols.NT_Query, 1, 1, 
		symbols.Symbols{  
			symbols.NT_MetricQuery,
		}, 
		Query1R1, 
	},
}

var slotIndex = map[Index]Label { 
	Index{ symbols.NT_LabelFilter,0,0 }: LabelFilter0R0,
	Index{ symbols.NT_LabelFilter,0,1 }: LabelFilter0R1,
	Index{ symbols.NT_LabelFilter,0,2 }: LabelFilter0R2,
	Index{ symbols.NT_LabelFilter,0,3 }: LabelFilter0R3,
	Index{ symbols.NT_LabelFilter,0,4 }: LabelFilter0R4,
	Index{ symbols.NT_LabelFilterOp,0,0 }: LabelFilterOp0R0,
	Index{ symbols.NT_LabelFilterOp,0,1 }: LabelFilterOp0R1,
	Index{ symbols.NT_LabelFilterOp,1,0 }: LabelFilterOp1R0,
	Index{ symbols.NT_LabelFilterOp,1,1 }: LabelFilterOp1R1,
	Index{ symbols.NT_LabelFilterOp,2,0 }: LabelFilterOp2R0,
	Index{ symbols.NT_LabelFilterOp,2,1 }: LabelFilterOp2R1,
	Index{ symbols.NT_LabelFilterOp,3,0 }: LabelFilterOp3R0,
	Index{ symbols.NT_LabelFilterOp,3,1 }: LabelFilterOp3R1,
	Index{ symbols.NT_LabelFilterOp,4,0 }: LabelFilterOp4R0,
	Index{ symbols.NT_LabelFilterOp,4,1 }: LabelFilterOp4R1,
	Index{ symbols.NT_LabelFilterOp,5,0 }: LabelFilterOp5R0,
	Index{ symbols.NT_LabelFilterOp,5,1 }: LabelFilterOp5R1,
	Index{ symbols.NT_LabelFilterOp,6,0 }: LabelFilterOp6R0,
	Index{ symbols.NT_LabelFilterOp,6,1 }: LabelFilterOp6R1,
	Index{ symbols.NT_LabelFilterOp,7,0 }: LabelFilterOp7R0,
	Index{ symbols.NT_LabelFilterOp,7,1 }: LabelFilterOp7R1,
	Index{ symbols.NT_LabelKey,0,0 }: LabelKey0R0,
	Index{ symbols.NT_LabelKey,0,1 }: LabelKey0R1,
	Index{ symbols.NT_LineFilter,0,0 }: LineFilter0R0,
	Index{ symbols.NT_LineFilter,0,1 }: LineFilter0R1,
	Index{ symbols.NT_LineFilter,0,2 }: LineFilter0R2,
	Index{ symbols.NT_LineFilterOp,0,0 }: LineFilterOp0R0,
	Index{ symbols.NT_LineFilterOp,0,1 }: LineFilterOp0R1,
	Index{ symbols.NT_LineFilterOp,1,0 }: LineFilterOp1R0,
	Index{ symbols.NT_LineFilterOp,1,1 }: LineFilterOp1R1,
	Index{ symbols.NT_LineFilterOp,2,0 }: LineFilterOp2R0,
	Index{ symbols.NT_LineFilterOp,2,1 }: LineFilterOp2R1,
	Index{ symbols.NT_LineFilterOp,3,0 }: LineFilterOp3R0,
	Index{ symbols.NT_LineFilterOp,3,1 }: LineFilterOp3R1,
	Index{ symbols.NT_LogQuery,0,0 }: LogQuery0R0,
	Index{ symbols.NT_LogQuery,0,1 }: LogQuery0R1,
	Index{ symbols.NT_LogQuery,0,2 }: LogQuery0R2,
	Index{ symbols.NT_LogSelector,0,0 }: LogSelector0R0,
	Index{ symbols.NT_LogSelector,0,1 }: LogSelector0R1,
	Index{ symbols.NT_LogSelector,0,2 }: LogSelector0R2,
	Index{ symbols.NT_LogSelector,0,3 }: LogSelector0R3,
	Index{ symbols.NT_LogSelectorMember,0,0 }: LogSelectorMember0R0,
	Index{ symbols.NT_LogSelectorMember,0,1 }: LogSelectorMember0R1,
	Index{ symbols.NT_LogSelectorMember,0,2 }: LogSelectorMember0R2,
	Index{ symbols.NT_LogSelectorMember,0,3 }: LogSelectorMember0R3,
	Index{ symbols.NT_LogSelectorMembers,0,0 }: LogSelectorMembers0R0,
	Index{ symbols.NT_LogSelectorMembers,0,1 }: LogSelectorMembers0R1,
	Index{ symbols.NT_LogSelectorMembers,1,0 }: LogSelectorMembers1R0,
	Index{ symbols.NT_LogSelectorMembers,1,1 }: LogSelectorMembers1R1,
	Index{ symbols.NT_LogSelectorMembers,1,2 }: LogSelectorMembers1R2,
	Index{ symbols.NT_LogSelectorMembers,1,3 }: LogSelectorMembers1R3,
	Index{ symbols.NT_LogSelectorMembersMaybe,0,0 }: LogSelectorMembersMaybe0R0,
	Index{ symbols.NT_LogSelectorMembersMaybe,1,0 }: LogSelectorMembersMaybe1R0,
	Index{ symbols.NT_LogSelectorMembersMaybe,1,1 }: LogSelectorMembersMaybe1R1,
	Index{ symbols.NT_LogSelectorOp,0,0 }: LogSelectorOp0R0,
	Index{ symbols.NT_LogSelectorOp,0,1 }: LogSelectorOp0R1,
	Index{ symbols.NT_LogSelectorOp,1,0 }: LogSelectorOp1R0,
	Index{ symbols.NT_LogSelectorOp,1,1 }: LogSelectorOp1R1,
	Index{ symbols.NT_LogSelectorOp,2,0 }: LogSelectorOp2R0,
	Index{ symbols.NT_LogSelectorOp,2,1 }: LogSelectorOp2R1,
	Index{ symbols.NT_LogSelectorOp,3,0 }: LogSelectorOp3R0,
	Index{ symbols.NT_LogSelectorOp,3,1 }: LogSelectorOp3R1,
	Index{ symbols.NT_MetricQuery,0,0 }: MetricQuery0R0,
	Index{ symbols.NT_MetricQuery,0,1 }: MetricQuery0R1,
	Index{ symbols.NT_MetricQuery,0,2 }: MetricQuery0R2,
	Index{ symbols.NT_MetricQuery,0,3 }: MetricQuery0R3,
	Index{ symbols.NT_MetricQuery,0,4 }: MetricQuery0R4,
	Index{ symbols.NT_MetricQuery,0,5 }: MetricQuery0R5,
	Index{ symbols.NT_MetricQuery,0,6 }: MetricQuery0R6,
	Index{ symbols.NT_MetricQuery,0,7 }: MetricQuery0R7,
	Index{ symbols.NT_MetricQuery,0,8 }: MetricQuery0R8,
	Index{ symbols.NT_MetricQuery,0,9 }: MetricQuery0R9,
	Index{ symbols.NT_MetricQuery,0,10 }: MetricQuery0R10,
	Index{ symbols.NT_MetricQuery,0,11 }: MetricQuery0R11,
	Index{ symbols.NT_MetricQuery,0,12 }: MetricQuery0R12,
	Index{ symbols.NT_MetricQuery,0,13 }: MetricQuery0R13,
	Index{ symbols.NT_MetricQuery,0,14 }: MetricQuery0R14,
	Index{ symbols.NT_NestedLabelKey,0,0 }: NestedLabelKey0R0,
	Index{ symbols.NT_NestedLabelKey,0,1 }: NestedLabelKey0R1,
	Index{ symbols.NT_NestedLabelKey,1,0 }: NestedLabelKey1R0,
	Index{ symbols.NT_NestedLabelKey,1,1 }: NestedLabelKey1R1,
	Index{ symbols.NT_NestedLabelKey,1,2 }: NestedLabelKey1R2,
	Index{ symbols.NT_NestedLabelKey,1,3 }: NestedLabelKey1R3,
	Index{ symbols.NT_Pipeline,0,0 }: Pipeline0R0,
	Index{ symbols.NT_Pipeline,0,1 }: Pipeline0R1,
	Index{ symbols.NT_Pipeline,1,0 }: Pipeline1R0,
	Index{ symbols.NT_Pipeline,1,1 }: Pipeline1R1,
	Index{ symbols.NT_Pipelines,0,0 }: Pipelines0R0,
	Index{ symbols.NT_Pipelines,0,1 }: Pipelines0R1,
	Index{ symbols.NT_Pipelines,1,0 }: Pipelines1R0,
	Index{ symbols.NT_Pipelines,1,1 }: Pipelines1R1,
	Index{ symbols.NT_Pipelines,1,2 }: Pipelines1R2,
	Index{ symbols.NT_PipelinesMaybe,0,0 }: PipelinesMaybe0R0,
	Index{ symbols.NT_PipelinesMaybe,1,0 }: PipelinesMaybe1R0,
	Index{ symbols.NT_PipelinesMaybe,1,1 }: PipelinesMaybe1R1,
	Index{ symbols.NT_Query,0,0 }: Query0R0,
	Index{ symbols.NT_Query,0,1 }: Query0R1,
	Index{ symbols.NT_Query,1,0 }: Query1R0,
	Index{ symbols.NT_Query,1,1 }: Query1R1,
}

var alternates = map[symbols.NT][]Label{ 
	symbols.NT_Query:[]Label{ Query0R0,Query1R0 },
	symbols.NT_LogQuery:[]Label{ LogQuery0R0 },
	symbols.NT_LogSelector:[]Label{ LogSelector0R0 },
	symbols.NT_LogSelectorMembersMaybe:[]Label{ LogSelectorMembersMaybe0R0,LogSelectorMembersMaybe1R0 },
	symbols.NT_LogSelectorMembers:[]Label{ LogSelectorMembers0R0,LogSelectorMembers1R0 },
	symbols.NT_LogSelectorMember:[]Label{ LogSelectorMember0R0 },
	symbols.NT_LabelKey:[]Label{ LabelKey0R0 },
	symbols.NT_LogSelectorOp:[]Label{ LogSelectorOp0R0,LogSelectorOp1R0,LogSelectorOp2R0,LogSelectorOp3R0 },
	symbols.NT_PipelinesMaybe:[]Label{ PipelinesMaybe0R0,PipelinesMaybe1R0 },
	symbols.NT_Pipelines:[]Label{ Pipelines0R0,Pipelines1R0 },
	symbols.NT_Pipeline:[]Label{ Pipeline0R0,Pipeline1R0 },
	symbols.NT_LineFilter:[]Label{ LineFilter0R0 },
	symbols.NT_LineFilterOp:[]Label{ LineFilterOp0R0,LineFilterOp1R0,LineFilterOp2R0,LineFilterOp3R0 },
	symbols.NT_LabelFilter:[]Label{ LabelFilter0R0 },
	symbols.NT_NestedLabelKey:[]Label{ NestedLabelKey0R0,NestedLabelKey1R0 },
	symbols.NT_LabelFilterOp:[]Label{ LabelFilterOp0R0,LabelFilterOp1R0,LabelFilterOp2R0,LabelFilterOp3R0,LabelFilterOp4R0,LabelFilterOp5R0,LabelFilterOp6R0,LabelFilterOp7R0 },
	symbols.NT_MetricQuery:[]Label{ MetricQuery0R0 },
}

