---
apiVersion: v1
kind: Service
metadata:
  name: loghousecluster
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: loghouse
      port: 3100
  selector:
    app: loghouse
---
apiVersion: v1
kind: Service
metadata:
  name: loghouse
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: 3100
  selector:
    app: loghouse
---
apiVersion: v1
kind: Service
metadata:
  name: loki-gateway
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3100
  selector:
    app: loghouse
