version: "3"
networks:
  loki:
services:
  loki:
    image: loghouse
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
  promtail:
    image: grafana/promtail:2.7.1
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
  fluentbit:
    image: fluent/fluent-bit
    volumes:
      - /var/log:/var/log
      - ./fluentbit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
