version: "3"
networks:
  loki:
volumes:
  loghouse-data:
  grafana-data:
services:
  loki:
    image: loghouse
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loghouse-data:/data
    networks:
      - loki
  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - /var/log:/var/log
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - loki
